###
POST http://localhost:3000/api/calarea
Content-Type: application/json

{
    "geometry": {"type": "Polygon","coordinates": [[ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0] ]]},
    "srid": 32647
}

###
POST http://localhost:3000/api/split
Content-Type: application/json

{
  "polygon": {"type": "Polygon", "coordinates": [[[98.94974063401833,18.80288760560407],[98.94974063401833,18.80274987614453],[98.95043452837308,18.80274987614453],[98.95043452837308,18.80288760560407],[98.94974063401833,18.80288760560407]]]},
  "line": {"type": "LineString", "coordinates": [[98.94995215272888,18.802934088357546],[98.94995954337315,18.802703212750473]]}, 
  "srid": 32647
}

###
GET http://localhost:3499/rub/api/users


###
POST http://localhost:3499/rub/api/layerlist
Content-Type: application/json

{
  "tb_name":     "nan",
  "tb_fullname": "tb_rub_nan",
  "remark":      "something"
}

###
GET https://landsmaps.dol.go.th/geoserver/LANDSMAPS/wms?service=WMS&version=1.1.1&request=GetFeatureInfo&layers=LANDSMAPS:V_PARCEL48&query_layers=LANDSMAPS:V_PARCEL48&bbox=103.29620361328124,14.691467285156245,103.29757690429686,14.69284057617188&width=256&height=256&srs=EPSG:4326&x=128&y=128&info_format=application/vnd.ogc.gml


###
GET https://landsmaps.dol.go.th/geoserver/LANDSMAPS/ows?service=WFS&version=2.0.0&request=GetFeature&typeName=LANDSMAPS:V_PARCEL48&outputFormat=GML3&srsName=EPSG:4326&bbox=103.29620361328124,14.691467285156245,103.29757690429686,14.69284057617188,EPSG:4326

###
GET https://landsmaps.dol.go.th/geoserver/LANDSMAPS/wms?transparent=true&format=image%2Fpng&viewparams=utmmap%3A563821624&=&service=WMS&version=1.1.1&request=GetMap&styles=&layers=LANDSMAPS%3AV_PARCEL48&bbox=103.29208374023436%2C14.694900512695314%2C103.2927703857422%2C14.695587158203125&width=256&height=256&srs=EPSG%3A4326&info_format=application/vnd.ogc.gml

###
GET https://landsmaps.dol.go.th/geoserver/LANDSMAPS/wms/reflect?layers=LANDSMAPS:V_PARCEL48&format=rss&viewparams=utmmap:563821624

### get gml
GET https://landsmaps.dol.go.th/geoserver/LANDSMAPS/wms?format=rss&viewparams=utmmap%3A563821624&=&service=WMS&version=1.1.1&request=GetMap&styles=&layers=LANDSMAPS%3AV_PARCEL48&bbox=103.29345703124999%2C14.694213867187504%2C103.29895019531247%2C14.699707031249995&width=256&height=256&srs=EPSG%3A4326

### get json
GET https://landsmaps.dol.go.th/geoserver/LANDSMAPS/wms?viewparams=utmmap%3A563821624&=&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=LANDSMAPS%3AV_PARCEL48&bbox=103.29372122%2C14.69413140%2C103.29372123%2C14.69413141&width=256&height=256&srs=EPSG%3A4326&query_layers=LANDSMAPS%3AV_PARCEL48&info_format=application%2Fjson&x=103&y=85

### get json
GET https://landsmaps.dol.go.th/geoserver/LANDSMAPS/wms?viewparams=utmmap:563821624&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=LANDSMAPS:V_PARCEL48&bbox=103.29372123,14.69413141,103.293721230.01,14.694131410.01&width=256&height=256&srs=EPSG:4326&query_layers=LANDSMAPS:V_PARCEL48&info_format=application/json&x=103&y=85


###
GET https://landsmaps.dol.go.th/Service/ProvinceService/configapi.json

### get pro ldd
GET https://landsmaps.dol.go.th/apiService/Master/GetProvince HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjEiLCJyZWdpc3Rlcl90eXBlX3NlcSI6IjgiLCJ1c2VyX2dyb3VwX2RhdGFfbGlzdCI6IjEsMSwwLDAsMCwwLDAsMSIsInBlcnNvbmFsX2lkIjoiIiwianRpIjoiNWJhMjhkMDUtYTM2NS00NDM3LTkzOTAtNDY2Mjg3ZTI1YTAwIiwiaWF0IjoiMDYvMTEvMjAyNSAwMzo1MDowMCIsIm5iZiI6MTc0OTYxMzgwMCwiZXhwIjoxNzQ5NzAwMjAwLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDozMDAwMS8iLCJhdWQiOiJMYW5kc01hcHMifQ._RO52KLrM8TMGwAXAtElFKPJRyCxtMLiz1d2zq6IPnwSF-SBnNhax4CXyy7SO3kDT2YON4ddYh5KaPr2juGIqg
Accept: application/json
Cookie: _ga=GA1.1.1019945317.1745203012; cookiesession1=678B2867F76490B74EAF42C2D1820121; incap_ses_297_3228816=lRCBMRCeFCVTNafP+CcfBNz8SGgAAAAAxSECWicWdW+k+IggiQqg/g==; visid_incap_3228816=xKJ5JaI9StOp2c9SoncI6tz8SGgAAAAAQkIPAAAAAACAJfO8Acoc+ynQiOJNGo+BXCVwMMj6RbiB; _ga_6X36FRLQTC=GS2.1.s1749613800$o8$g1$t1749614093$j46$l0$h0; _ga_SLMHW2S3XN=GS2.1.s1749613796$o7$g1$t1749614144$j60$l0$h0

### get amp ldd
GET https://landsmaps.dol.go.th/apiService/Master/GetAmphoe/41 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjEiLCJyZWdpc3Rlcl90eXBlX3NlcSI6IjgiLCJ1c2VyX2dyb3VwX2RhdGFfbGlzdCI6IjEsMSwwLDAsMCwwLDAsMSIsInBlcnNvbmFsX2lkIjoiIiwianRpIjoiNWJhMjhkMDUtYTM2NS00NDM3LTkzOTAtNDY2Mjg3ZTI1YTAwIiwiaWF0IjoiMDYvMTEvMjAyNSAwMzo1MDowMCIsIm5iZiI6MTc0OTYxMzgwMCwiZXhwIjoxNzQ5NzAwMjAwLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDozMDAwMS8iLCJhdWQiOiJMYW5kc01hcHMifQ._RO52KLrM8TMGwAXAtElFKPJRyCxtMLiz1d2zq6IPnwSF-SBnNhax4CXyy7SO3kDT2YON4ddYh5KaPr2juGIqg
Accept: application/json
Cookie: _ga=GA1.1.1019945317.1745203012; cookiesession1=678B2867F76490B74EAF42C2D1820121; incap_ses_297_3228816=lRCBMRCeFCVTNafP+CcfBNz8SGgAAAAAxSECWicWdW+k+IggiQqg/g==; visid_incap_3228816=xKJ5JaI9StOp2c9SoncI6tz8SGgAAAAAQkIPAAAAAACAJfO8Acoc+ynQiOJNGo+BXCVwMMj6RbiB; _ga_6X36FRLQTC=GS2.1.s1749613800$o8$g1$t1749614093$j46$l0$h0; _ga_SLMHW2S3XN=GS2.1.s1749613796$o7$g1$t1749614144$j60$l0$h0

### 
GET https://landsmaps.dol.go.th/apiService/LandsMaps/GetParcelByParcelNo/86/01/92561 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjEiLCJyZWdpc3Rlcl90eXBlX3NlcSI6IjgiLCJ1c2VyX2dyb3VwX2RhdGFfbGlzdCI6IjEsMSwwLDAsMCwwLDAsMSIsInBlcnNvbmFsX2lkIjoiIiwianRpIjoiMjQ2NDUyZjYtZGU0Yi00OWZiLWI1ZDItNGNmOGRlZDk5YzEwIiwiaWF0IjoiMDYvMTAvMjAyNSAwODozMDo1MyIsIm5iZiI6MTc0OTU0NDI1MywiZXhwIjoxNzQ5NjMwNjUzLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDozMDAwMS8iLCJhdWQiOiJMYW5kc01hcHMifQ.Xm8o2RAF5hqRAkAYIEHw4JFWjlhMdnDBBeNtfZ0YYnRE_c_x8VVg8SNoUvm8t7Kir1qvyvPIvrcuXfOadt2KTA
Accept: application/json
Cookie: _ga=GA1.1.1019945317.1745203012; cookiesession1=678B2867F76490B74EAF42C2D1820121; incap_ses_297_3228816=lRCBMRCeFCVTNafP+CcfBNz8SGgAAAAAxSECWicWdW+k+IggiQqg/g==; visid_incap_3228816=xKJ5JaI9StOp2c9SoncI6tz8SGgAAAAAQkIPAAAAAACAJfO8Acoc+ynQiOJNGo+BXCVwMMj6RbiB; _ga_6X36FRLQTC=GS2.1.s1749613800$o8$g1$t1749614093$j46$l0$h0; _ga_SLMHW2S3XN=GS2.1.s1749613796$o7$g1$t1749614144$j60$l0$h0

###
GET http://localhost:3499/rub/api/ldd_getpacelbypacelnumber/32/05/30980

###
GET https://landsmaps.dol.go.th/apiService/LandsMaps/GetParcelByLatLon/10.677941234615663/99.05967593193054
Authorization: Bearer  eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjEiLCJyZWdpc3Rlcl90eXBlX3NlcSI6IjgiLCJ1c2VyX2dyb3VwX2RhdGFfbGlzdCI6IjEsMSwwLDAsMCwwLDAsMSIsInBlcnNvbmFsX2lkIjoiIiwianRpIjoiNTllZGMxMTEtY2Q4OS00NzVjLWI5NjktMTA5MDI4YTczMTk0IiwiaWF0IjoiMDYvMTEvMjAyNSAxMDo0MTo0NSIsIm5iZiI6MTc0OTYzODUwNSwiZXhwIjoxNzQ5NzI0OTA1LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDozMDAwMS8iLCJhdWQiOiJMYW5kc01hcHMifQ.ZMJ8ZUuBDxCLIs8a8xX8w4VDax-DNZotJZyRPnP8aQ6YroOYi-LdnFVnefDdCJjEqerFTdEhilq76LntTTACBg

### get json
GET https://landsmaps.dol.go.th/geoserver/LANDSMAPS/wms?viewparams=utmmap%3A563821624&=&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=LANDSMAPS%3AV_PARCEL48&bbox=103.29372122%2C14.69413140%2C103.29372123%2C14.69413141&width=256&height=256&srs=EPSG%3A4326&query_layers=LANDSMAPS%3AV_PARCEL48&info_format=application%2Fjson&x=103&y=85


###
GET http://localhost:3499/rub/api/ldd_getpacelbylatlng/10.449831007673284/99.16521549224855

###
GET https://landsmaps.dol.go.th/apiService/LandsMaps/GetParcelByParcelNo/86/01/92651
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjEiLCJyZWdpc3Rlcl90eXBlX3NlcSI6IjgiLCJ1c2VyX2dyb3VwX2RhdGFfbGlzdCI6IjEsMSwwLDAsMCwwLDAsMSIsInBlcnNvbmFsX2lkIjoiIiwianRpIjoiNTllZGMxMTEtY2Q4OS00NzVjLWI5NjktMTA5MDI4YTczMTk0IiwiaWF0IjoiMDYvMTEvMjAyNSAxMDo0MTo0NSIsIm5iZiI6MTc0OTYzODUwNSwiZXhwIjoxNzQ5NzI0OTA1LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDozMDAwMS8iLCJhdWQiOiJMYW5kc01hcHMifQ.ZMJ8ZUuBDxCLIs8a8xX8w4VDax-DNZotJZyRPnP8aQ6YroOYi-LdnFVnefDdCJjEqerFTdEhilq76LntTTACBg
Accept: application/json
# Cookie: _ga=GA1.1.1019945317.1745203012; cookiesession1=678B2867F76490B74EAF42C2D1820121; incap_ses_297_3228816=lRCBMRCeFCVTNafP+CcfBNz8SGgAAAAAxSECWicWdW+k+IggiQqg/g==; visid_incap_3228816=xKJ5JaI9StOp2c9SoncI6tz8SGgAAAAAQkIPAAAAAACAJfO8Acoc+ynQiOJNGo+BXCVwMMj6RbiB; _ga_6X36FRLQTC=GS2.1.s1749613800$o8$g1$t1749614093$j46$l0$h0; _ga_SLMHW2S3XN=GS2.1.s1749613796$o7$g1$t1749614144$j60$l0$h0

###
Get https://landsmaps.dol.go.th/apiService/LandsMaps/GetParcelByParcelNo/32/05/30980
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjEiLCJyZWdpc3Rlcl90eXBlX3NlcSI6IjgiLCJ1c2VyX2dyb3VwX2RhdGFfbGlzdCI6IjEsMSwwLDAsMCwwLDAsMSIsInBlcnNvbmFsX2lkIjoiIiwianRpIjoiOWJhZGEwYzctYzJjOS00Zjc3LWIzODEtYjI5OTcyNzAyOGEwIiwiaWF0IjoiMDYvMTEvMjAyNSAwMzo1NDozOCIsIm5iZiI6MTc0OTYxNDA3OCwiZXhwIjoxNzQ5NzAwNDc4LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDozMDAwMS8iLCJhdWQiOiJMYW5kc01hcHMifQ.jZrc4i4ApImgqsgx4-Yr2hVqfbpQFsoc2TZp4JswXIFYlUx4YrxElekkgJEGyjoZSbecZEDfEwx0T5lEF0KEvQ
Accept: application/json
Cookie: _ga=GA1.1.1019945317.1745203012; cookiesession1=678B2867F76490B74EAF42C2D1820121; incap_ses_297_3228816=lRCBMRCeFCVTNafP+CcfBNz8SGgAAAAAxSECWicWdW+k+IggiQqg/g==; visid_incap_3228816=xKJ5JaI9StOp2c9SoncI6tz8SGgAAAAAQkIPAAAAAACAJfO8Acoc+ynQiOJNGo+BXCVwMMj6RbiB; _ga_6X36FRLQTC=GS2.1.s1749613800$o8$g1$t1749614093$j46$l0$h0; _ga_SLMHW2S3XN=GS2.1.s1749613796$o7$g1$t1749614144$j60$l0$h0

###
GET https://landsmaps.dol.go.th/geoserver/LANDSMAPS/wms?viewparams=utmmap%3A563821624&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=LANDSMAPS%3AV_PARCEL47%2CLANDSMAPS%3AV_PARCEL48&bbox=103.29372123%2C14.69413141%2C103.293722%2C14.694132&width=256&height=256&srs=EPSG%3A4326&query_layers=LANDSMAPS%3AV_PARCEL47%2CLANDSMAPS%3AV_PARCEL48&info_format=application%2Fjson&x=128&y=128


###
POST http://localhost:3499/rub/api/area
Content-Type: application/json

{
  "type":"Feature",
  "geometry":{
    "type":"MultiPolygon",
    "coordinates":[[[[99.216709459,10.79541527],[99.216499,10.795136],[99.216057,10.794823],[99.215051,10.79585],[99.215408,10.795882],[99.215504,10.795974],[99.215553,10.796106],[99.215569,10.796274],[99.21563,10.796332],[99.215708,10.796351],[99.215809332,10.796426326],[99.216709459,10.79541527]]]]},"properties":{"id":1,"sub_id":"1","app_no":"588602100017","shpsplit_sqm":"25986.9064396742","classtype":null}
}

###
GET http://localhost:3499/rub/api/


###
PUT http://localhost:3499/rub/api/update_ownerlanduse/rayong_point_v3
Content-Type: application/json
{
  "id": 1,
  "sub_id": "1-2",
  "ownertype": "rubber",
  "displayName": "napatsorn duhae"
}

### post sub id
POST http://localhost:3499/rub/api/collected_feat
Content-Type: application/json

{
  "id_list": ["1-1", "1-2-2"],
  "tb": "reclass_rub0_satun_v1_pp"
}


### get test
GET http://localhost:3499/rub/api/test

###
collected_feat




