services:
  postgis:
    platform: linux/amd64
    image: postgis/postgis:latest
    container_name: rub_postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rub1234
      - POSTGRES_DB=postgres
    ports:
      - 5400:5432
    volumes:
      - ./postgis:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    networks:
      - rub-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  nodejs:
    build: ./nodejs
    container_name: rub_nodejs
    restart: always
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=postgis
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=rub1234
      - DB_NAME=rub2
    env_file:
      - .env
    depends_on:
      - postgis
    volumes:
      - ./nodejs:/usr/src/app
    ports:
      - "3400:3000"
    networks:
      - rub-network
    command: sh -c "npm i -g nodemon && nodemon server.js"
networks:
  rub-network:
    driver: bridge

volumes:
  pgdata:
