/**
 * convert_shpall.js
 * Reads all .shp files from ../shpall/ subfolders and produces two files:
 *
 *   ../postgis/shpall.geojson  — GeoJSON FeatureCollection (with _bbox per feature)
 *                                 used by the API for bbox-filtered serving
 *
 *   ../postgis/shpall.sql      — PostgreSQL SQL file with DDL + INSERT data
 *                                 run with: psql -U postgres -d rub2 -f shpall.sql
 *
 * Run from the nodejs/ directory:
 *   node convert_shpall.js
 *
 * Both files are written as streams to avoid running out of memory.
 */

require('dotenv').config();
const shapefile = require('shapefile');
const fs        = require('fs');
const path      = require('path');

const DB_NAME = process.env.DB_NAME || 'rub2';
const DB_USER = process.env.DB_USER || 'postgres';

const SHPALL_DIR  = path.join(__dirname, '..', '..', 'shpnew', 'shpall');
const GEOJSON_OUT = path.join(__dirname, '..', 'postgis', 'shpall.geojson');
const SQL_OUT     = path.join(__dirname, '..', 'postgis', 'shpall.sql');

// ── helpers ──────────────────────────────────────────────────────────────────

function computeBbox(geom) {
    let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
    function walk(c) {
        if (typeof c[0] === 'number') {
            if (c[0] < minX) minX = c[0];
            if (c[1] < minY) minY = c[1];
            if (c[0] > maxX) maxX = c[0];
            if (c[1] > maxY) maxY = c[1];
        } else { for (const item of c) walk(item); }
    }
    walk(geom.coordinates);
    return [+minX.toFixed(6), +minY.toFixed(6), +maxX.toFixed(6), +maxY.toFixed(6)];
}

function sqlEsc(val) {
    if (val === null || val === undefined) return 'NULL';
    return "'" + String(val).replace(/'/g, "''") + "'";
}

function featureToSqlValues(f, id) {
    const p = f.properties || {};
    const geomJson = JSON.stringify({ type: f.geometry.type, coordinates: f.geometry.coordinates })
                         .replace(/'/g, "''");
    return `(${[
        id,
        sqlEsc(p.OBJECTID),
        sqlEsc(p.FARM_IDC),
        sqlEsc(p.FARM_NAME),
        sqlEsc(p.FARM_MOBIL),
        sqlEsc(p.LAND_TYPE),
        sqlEsc(p.LAND_RIGHT),
        sqlEsc(p.LAND_LOCAT),
        sqlEsc(p.LAND_SEQ),
        sqlEsc(p.LAND_NAME),
        sqlEsc(p.LAND_NO),
        sqlEsc(p.LAND_RAWAN),
        sqlEsc(p.UTM_ZONE),
        sqlEsc(p.CENTROID_X),
        sqlEsc(p.CENTROID_Y),
        sqlEsc(p.GID),
        sqlEsc(p.GROW_RAI),
        sqlEsc(p.LAND_RAI),
        sqlEsc(p.GROW_YEAR),
        sqlEsc(p.RUBBER_TYP),
        sqlEsc(p.GROW_QTY),
        sqlEsc(p.Shape_Leng),
        sqlEsc(p.Shape_Area),
        `ST_Multi(ST_SetSRID(ST_GeomFromGeoJSON('${geomJson}'::text),4326))`
    ].join(',')})`;
}

async function drain(ws) {
    if (!ws.write('')) return;
    await new Promise(r => ws.once('drain', r));
}

async function write(ws, data) {
    if (!ws.write(data)) {
        await new Promise(r => ws.once('drain', r));
    }
}

// ── SQL DDL header ────────────────────────────────────────────────────────────

const SQL_HEADER = `\\c ${DB_NAME}
-- Auto-generated by convert_shpall.js
-- Shapefile data 2026: all regions combined

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', 'public', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Drop and recreate table with latest data
DROP TABLE IF EXISTS public.shpall CASCADE;

CREATE TABLE public.shpall (
    id integer NOT NULL,
    objectid text,
    farm_idc text,
    farm_name text,
    farm_mobil text,
    land_type text,
    land_right text,
    land_locat text,
    land_seq text,
    land_name text,
    land_no text,
    land_rawan text,
    utm_zone text,
    centroid_x text,
    centroid_y text,
    gid text,
    grow_rai text,
    land_rai text,
    grow_year text,
    rubber_typ text,
    grow_qty text,
    shape_leng text,
    shape_area text,
    geom public.geometry(MultiPolygon,4326)
);

ALTER TABLE public.shpall OWNER TO ${DB_USER};

CREATE SEQUENCE public.shpall_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

ALTER SEQUENCE public.shpall_id_seq OWNER TO ${DB_USER};
ALTER SEQUENCE public.shpall_id_seq OWNED BY public.shpall.id;
ALTER TABLE ONLY public.shpall ALTER COLUMN id SET DEFAULT nextval('public.shpall_id_seq'::regclass);

-- Spatial index for fast bbox queries
CREATE INDEX shpall_geom_idx ON public.shpall USING GIST (geom);

-- ─── Data ────────────────────────────────────────────────────────────────────

`;

const INSERT_COLS = `INSERT INTO public.shpall ` +
    `(id,objectid,farm_idc,farm_name,farm_mobil,land_type,land_right,land_locat,` +
    `land_seq,land_name,land_no,land_rawan,utm_zone,centroid_x,centroid_y,gid,` +
    `grow_rai,land_rai,grow_year,rubber_typ,grow_qty,shape_leng,shape_area,geom) VALUES\n`;

const BATCH_SIZE = 200; // rows per INSERT statement

// ── main ──────────────────────────────────────────────────────────────────────

async function main() {
    const subfolders = fs.readdirSync(SHPALL_DIR, { withFileTypes: true })
        .filter(d => d.isDirectory()).map(d => d.name).sort();

    const geoStream = fs.createWriteStream(GEOJSON_OUT, { encoding: 'utf8' });
    const sqlStream = fs.createWriteStream(SQL_OUT,     { encoding: 'utf8' });

    await write(geoStream, '{"type":"FeatureCollection","features":[\n');
    await write(sqlStream, SQL_HEADER);

    let totalFeatures = 0;
    let batchRows = [];   // accumulated rows for current INSERT batch
    let firstFeature = true;

    async function flushBatch(final = false) {
        if (batchRows.length === 0) return;
        const sql = 'BEGIN;\n' + INSERT_COLS + batchRows.join(',\n') + ';\nCOMMIT;\n\n';
        await write(sqlStream, sql);
        batchRows = [];
    }

    for (const folder of subfolders) {
        const folderPath = path.join(SHPALL_DIR, folder);
        const shpFiles = fs.readdirSync(folderPath)
            .filter(f => f.toLowerCase().endsWith('.shp')).sort();

        for (const shpFile of shpFiles) {
            const shpPath = path.join(folderPath, shpFile);
            console.log(`อ่าน: ${folder}/${shpFile}`);
            let fileCount = 0;

            try {
                const source = await shapefile.open(shpPath, undefined, { encoding: 'UTF-8' });
                let result;
                while (!(result = await source.read()).done) {
                    const f = result.value;
                    if (!f || !f.geometry) continue;

                    totalFeatures++;
                    fileCount++;
                    const id = totalFeatures;

                    // ── GeoJSON ──
                    f.properties = f.properties || {};
                    f.properties._bbox = computeBbox(f.geometry);
                    const geoLine = (firstFeature ? '' : ',\n') + JSON.stringify(f);
                    await write(geoStream, geoLine);
                    firstFeature = false;

                    // ── SQL ──
                    batchRows.push(featureToSqlValues(f, id));
                    if (batchRows.length >= BATCH_SIZE) await flushBatch();
                }
                console.log(`  → ${fileCount} แปลง`);
            } catch (err) {
                console.error(`  ข้ามไฟล์ ${shpFile}: ${err.message}`);
            }
        }
    }

    // flush remaining rows
    await flushBatch(true);

    // ── update sequence ──
    await write(sqlStream,
        `SELECT setval('public.shpall_id_seq', ${totalFeatures}, true);\n`);

    await write(geoStream, '\n]}');

    // close streams
    await Promise.all([
        new Promise(r => { geoStream.end(); geoStream.on('finish', r); }),
        new Promise(r => { sqlStream.end(); sqlStream.on('finish', r); }),
    ]);

    console.log(`\nบันทึกสำเร็จ:`);
    console.log(`  GeoJSON: ${GEOJSON_OUT}`);
    console.log(`  SQL:     ${SQL_OUT}`);
    console.log(`รวมทั้งหมด: ${totalFeatures} แปลง`);
    console.log(`\nวิธีนำเข้าฐานข้อมูล:`);
    console.log(`  psql -U ${DB_USER} -d ${DB_NAME} -f "${SQL_OUT}"`);
}

main().catch(err => {
    console.error('เกิดข้อผิดพลาด:', err);
    process.exit(1);
});
